In [ ]:
import numpy as np

class HopfieldNetwork:

  def __init__(self, num_neurons) :

    self.num_neurons = num_neurons
    self.weights = np.zeros((num_neurons, num_neurons))

  def train (self, input_patterns):
    rows,columns = input_patterns.shape
    for pattern in input_patterns:
      pattern = np.reshape(pattern, (self.num_neurons, 1))
      self.weights += np.dot(pattern, pattern.T) 
      np.fill_diagonal (self.weights, 0)
    self.weights = self.weights/rows

  def predict (self, input_pattern):
    
    for pattern in input_pattern:
      x = np.array(pattern)
      y = np.array(pattern)
       
      for i in range(len(y)):
        # print("y[",i,"] is",y[i] )
        # print("x[",i,"] is",x[i] )
        # print("corresponding weights", self.weights[i])
        # print("Dot is ", np.dot(y,self.weights[i]))
        activation = np.sign(x[i]+ np.dot(y,self.weights[i]))
        if(activation  == 0):
          activation = 1
        y[i] = activation

        # print("new y[",i,"] is",y[i] )
        # print("y is ", y)
      print("for ",x ,"output is", y)
    

In [ ]:
# Number of neurons = length of bit
# Synchronous updation
num_neurons =4
HopField = HopfieldNetwork(num_neurons) 
input_patterns= np.array([[1,1,1,1],[-1,-1,-1,1],[-1,-1,1,1]])
HopField.train(input_patterns)

input_pattern = np.array([[1,-1,-1,1],[1,-1,1,1]])
HopField.predict(input_pattern)



for  [ 1 -1 -1  1] output is [-1 -1 -1  1]
for  [ 1 -1  1  1] output is [1 1 1 1]


[[ 1  1  1]
 [-1 -1 -1]]
pattern is  [1 1 1]
[1 1 1]
weight is [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
pattern is  [-1 -1 -1]
[-1 -1 -1]
weight is [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
